#!/usr/bin/env bash

set -e
# Put instructions to compile source code, remove this file if the language does not require this stage


case "${PISTON_LANGUAGE}" in
    c)
        gcc -std=c11 -fdiagnostics-format=json *.c -lm
        ;;
    c++)
        g++ -std=c++17 -fdiagnostics-format=json *.cpp
        ;;
    d)
        gdc *.d
        ;;
    fortran)
        gfortran *.f90
        ;;
    *)
        echo "How did you get here? (${PISTON_LANGUAGE})"
        exit 1
        ;;
esac

chmod +x a.out
