# Common configuration for all services
#
# This file should **NOT** be used on its own. Instead, you should copy/symlink
# either of docker-compose.dev.yml or docker-compose.prod.yml to
# docker-compose.override.yml as appropriate and use that instead.
#
# Development:
#
#   ln -s docker-compose.dev.yml docker-compose.override.yml
#
# Production:
#
#   ln -s docker-compose.prod.yml docker-compose.override.yml
#
# Docker Compose will then combine the common settings here, with the
# customizations in the override file, and everything will work wonderfully.
version: '3'
services:
  webapp:
    build: ./webapp
    depends_on:
      - rce
    ports:
      - '3000:3000'

  # The remote code execution engine. For now, this is a quick and dirty engine.
  # It MUST be replaced with something like Jobe or Piston in production.
  rce:
    build: ./rce
    init: true
