# This is hard-coded for how I will deploy it on beckett4
version: '3'
services:
  webapp:
    build:
      context: ./webapp
      target: production
      args:
        # My user/group IDs on the machine. Not sure why they're off by one.
        GROUP_ID: 1093
        USER_ID: 1092
    restart: always
    environment:
      NODE_ENV: production
      DATABASE_PATH: /app/run/answers.sqlite3
      # SvelteKit relies on these to know the correct origin:
      PROTOCOL_HEADER: x-forwarded-proto
      HOST_HEADER: x-forwarded-host
      # Nginx has to be configured to pass "https" and the hostname (e.g., beckett4.ucd.ie), respectively
      # See: https://kit.svelte.dev/docs/adapter-node#environment-variables-origin-protocolheader-and-hostheader
    volumes:
      - /home/eddie/oq/run/:/app/run/

  rce:
    restart: always
    environment:
      # We still don't need that many workers
      GUNICORN_WORKERS: 4
