version: '3'
services:
    webapp:
        build:
            context: ./webapp
            target: production
        environment:
            DATABASE_PATH: '/app/run/answers.sqlite3'
        ports:
            - '3000:3000'
        volumes:
            # XXX: TEMPORARY
            - /tmp/oq/run:/app/run/

    # The remote code execution engine. For now, this is a quick and dirty engine.
    # It MUST be replaced with something like Jobe or Piston in production.
    rce:
        build: ./rce
        init: true
        ports:
            - '8000:8000'
        environment:
            GUNICORN_WORKERS: 2
