version: '3'
services:
    webapp:
        build:
            context: ./webapp
            target: production
        environment:
            NODE_ENV: production
            DATABASE_PATH: '/app/run/answers.sqlite3'
            # SvelteKit relies on this to know the correct origin:
            # In real prod, behind nginx, use PROTOCOL_HEADER=x-forwarded-proto HOST_HEADER=x-forwarded-host
            # See: https://kit.svelte.dev/docs/adapter-node#environment-variables-origin-protocolheader-and-hostheader
            ORIGIN: 'http://localhost:3000'
        ports:
            - '3000:3000'
        volumes:
            # XXX: TEMPORARY
            - /tmp/oq/run:/app/run/

    # The remote code execution engine. For now, this is a quick and dirty engine.
    # It MUST be replaced with something like Jobe or Piston in production.
    rce:
        build: ./rce
        init: true
        ports:
            - '8000:8000'
        environment:
            GUNICORN_WORKERS: 2
