<script>
    import ConsentCheckbox from '$lib/components/ConsentCheckbox.svelte';

    let participation = false;
    let questionnaire = false;
    let pseudonymised = false;
    let dataCollection = false;
    let interactionLogged = false;
    let dataUsage = false;
    $: canContinue =
        participation &&
        questionnaire &&
        pseudonymised &&
        dataCollection &&
        interactionLogged &&
        dataUsage;

    // Use Intl to format the date in the Irish locale
    let today = new Intl.DateTimeFormat('en-IE', { dateStyle: 'short' }).format(new Date());
</script>

<header>
    <h1>Adult participation consent form</h1>
</header>

<form method="POST">
    <p>I consent to the following:</p>

    <ConsentCheckbox name="participation" bind:value={participation}>
        I have read this information sheet and have had time to consider whether to take part in the
        data collection. I understand that my participation is voluntary (it is my choice) and that
        I am free to withdraw from the research up until I submit this form without disadvantage. I
        agree to take part in this research.
    </ConsentCheckbox>

    <ConsentCheckbox name="questionnaire" bind:value={questionnaire}>
        I understand that, as part of this research project, I will be asked to take part in a
        questionnaire as well as take part in a programming task with a code editor that logs my
        activity, including the source code that I write.
    </ConsentCheckbox>

    <ConsentCheckbox name="pseudonymised" bind:value={pseudonymised}>
        I understand that my name will not be identified in any way and that the data generated by
        me will be appropriately pseudonymised during the data collection.
    </ConsentCheckbox>

    <ConsentCheckbox name="data-collection" bind:value={dataCollection}>
        I am voluntarily agreeing to have my data collected through this application and stored in
        encrypted laptop devices for the duration of the study.
    </ConsentCheckbox>

    <ConsentCheckbox name="interaction-logged" bind:value={interactionLogged}>
        I am voluntarily agreeing to have my interaction with the code editor logged only during the
        programming task and later stored in encrypted laptop devices for the duration of the study.
    </ConsentCheckbox>

    <ConsentCheckbox name="data-usage" bind:value={dataUsage}>
        I agree that the data can be used in publication of higher degrees and scientific
        publications.
    </ConsentCheckbox>

    <p>Signed: {today}</p>
    <button type="submit" disabled={!canContinue}>Continue</button>
</form>
