# Assumes you have already pulled Piston, installed packages, and performed
# necessary customizations to data/piston/packages
FROM ghcr.io/eddieantonio/piston:20231101@sha256:6500f2af69ce18fe16ca9a0ba7b0ea895366fc0efa46860c03d1d3c8a6cd270d
COPY ./data/piston/packages /piston/packages
