import { CONDITIONS, type Assignment, type Condition } from '$lib/types';
import { taskNames } from './tasks';

export const assignmentGenerator = generateAssignments();

/**
 * Infinite generator of all possible assignments.
 *
 * This generate will return random assignments, but ensures that all possible
 * assignments are equally likely. That is, task and condition are both randomly
 * assigned, but counterbalanced.
 *
 * NOTE: assignments will be counterbalanced AS LONG AS only one server process
 * is creating the assignments and does not restart between all assignments!
 */
function* generateAssignments(): Generator<Assignment[], undefined, undefined> {
    const allPossibleAssignments = [];
    for (const taskOrder of permutations(taskNames())) {
        for (const prezOrder of permutations(CONDITIONS)) {
            const assignments: Assignment[] = taskOrder.map((task, index) => ({
                task,
                condition: prezOrder[index] as Condition
            }));
            allPossibleAssignments.push(assignments);
        }
    }

    while (true) {
        shuffle(allPossibleAssignments);
        yield* allPossibleAssignments;
    }
}

// Fisher-Yates shuffle, as generated by GitHub Copilot.
// It starts from the end, which is not the way I usually implement it,
// but it honestly do not matter.
function shuffle<T>(array: T[]): T[] {
    for (let i = array.length - 1; i > 0; i--) {
        // i + 1 so that we randomly pick to swap the element with itself.
        // (hint: you're supposed to be able to swap an element with itself, or
        //  else you're not shuffling properly).
        const j = Math.floor(Math.random() * (i + 1));
        [array[i], array[j]] = [array[j], array[i]];
    }
    return array;
}

// Returns an array of all permutations of the given array.
// Generated by GitHub Copilot.
function permutations<T>(array: readonly T[]): T[][] {
    if (array.length <= 1) return [[...array]];

    const result = [];
    for (let i = 0; i < array.length; i++) {
        const element = array[i];
        // Slice out the current element.
        const rest = array.slice(0, i).concat(array.slice(i + 1));
        // Recurse to get permutations of the rest of the array.
        const restPermutations = permutations(rest);
        for (const perm of restPermutations) {
            result.push([element, ...perm]);
        }
    }
    return result;
}
